FROM debian:buster

LABEL \
  org.label-schema.schema-version="1.0" \
  org.label-schema.name="nexsre/debian:buster" \
  org.label-schema.vcs-url="https://github.com/Nexchard/instantbox-images" \
  maintainer="Nexsre Team <team@nexsre.com>"

WORKDIR /home


COPY ./ttyd_linux.x86_64 /usr/bin/

RUN chmod +x /usr/bin/ttyd_linux.x86_64

CMD ["ttyd_linux.x86_64", "-p", "1588", "bash"]

EXPOSE 1588

ARG BUILD_DATE
ARG VCS_REF
LABEL \
  org.label-schema.build-date=$BUILD_DATE \
  org.label-schema.vcs-ref=$VCS_REF
